name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Build Go application
      run: go build -o myapp

    - name: Archive production artifacts
      run: tar -czvf myapp.tar.gz myapp

    - name: Copy files via SSH
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.AZURE_VM_IP }}
        username: ${{ secrets.AZURE_VM_USERNAME }}
        key: ${{ secrets.AZURE_VM_SSH_KEY }}
        source: "myapp.tar.gz"
        target: "/home/yourusername/"

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: SSH into Azure VM and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AZURE_VM_IP }}
        username: ${{ secrets.AZURE_VM_USERNAME }}
        key: ${{ secrets.AZURE_VM_SSH_KEY }}
        script: |
          tar -xzvf /home/yourusername/myapp.tar.gz
          sudo docker build -t myapp .
          sudo docker run -d -p 8080:8080 myapp
